apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: hello-world-workflow
spec:
  retryStrategy:
    retryPolicy: OnError
    limit: 1
  entrypoint: whalesay
  arguments:
    parameters:
      - name: message
        value: bye world
  templates:
    - name: whalesay
      inputs:
        parameters:
          - name: message
      container:
        image: docker/whalesay
        command: [ cowsay ]
        args: [ "{{inputs.parameters.message}}" ] 
